### ISSUE TITLE
API Call Returns an Empty Array

### ISSUE THREAD

**Issue by ercole89** [AstarNetwork/astar-token-api#132]
Hello,

I've been attempting to use the Astar API and have encountered an issue. Even when I test it on the website, I run into the same problem. Specifically, when I make certain calls, such as this one:

https://api.astar.network/api/v3/astar/dapps-staking/stakerslist/0xa602d021da61ec4cc44dedbd4e3090a05c97a435

It consistently returns an empty array '[]'.

Is there a configuration setting I might be missing, or could this be a bug in the API? Any guidance or suggestions would be greatly appreciated.

Thank you for your assistance.

**Comment by bobo-k2** [comment]
Hi, the reason why you are getting empty array is because this endpoint is for dApp staking v3 and v3 is not deployed to Astar yet. The endpoint returns results for Shibuya at the moment (https://api.astar.network/api/v3/shibuya/dapps-staking/stakerslist/0xf3824888ecca4514dd776f0db38d6530ab8fb280). Values for Shiden and Astar will be available after dApp staking v3 deployment on those networks.

**Comment by bobo-k2** [comment]
Closing this as solved with Dapp Staking v3 release on Astar
